resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/bcampoli/pcf-attendee-service-code.git
    branch: master
- name: deploy-attendee-service
  type: cf
  source:
    api: api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: william-campoli-org
    space: development
    skip_cert_check: true


jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: test_deploy
  public: true
  plan:
  - get: attendee-service-source-temp
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest-temp.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test_deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-bunodont-desolator-temp.cfapps.io

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [smoke-test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test_true
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test-deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-bunodont-desolator.cfapps.io
