resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/bcampoli/pcf-attendee-service-code.git
    branch: master
- name: deploy-attendee-service
  type: cf
  source:
    api: api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true


jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest-temp.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://{{cf-app-suffix-temp}}-{{cf-route}}-temp.{{cf-app-domain}}

- name: re-route
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [smoke_test]
  - task: re-route
    file: attendee-service-source/ci/tasks/re-route.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_API: {{cf-api}}
      CF_ORG: {{cf-org}}
      CF_USER: {{cf-user}}
      CF_PWD: {{cf-password}}
      CF_SPACE: {{cf-space}}
      CF_APP_SUFFIX_TEMP: {{cf-app-suffix-temp}}
      CF_DOMAIN: {{cf-app-domain}}
      CF_ROUTE: {{cf-route}}

- name: smoke_test_true
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [re-route]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://{{cf-app-suffix}}-{{cf-route}}.{{cf-app-domain}}

- name: remove_old
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [smoke_test_true]
  - task: remove_old
    file: attendee-service-source/ci/tasks/remove_old.yml
    params:
      CF_APP_SUFFIX: {{cf-app-suffix}}
      CF_API: {{cf-api}}
      CF_ORG: {{cf-org}}
      CF_USER: {{cf-user}}
      CF_PWD: {{cf-password}}
      CF_SPACE: {{cf-space}}
      CF_APP_SUFFIX_TEMP: {{cf-app-suffix-temp}}
      CF_DOMAIN: {{cf-app-domain}}
      CF_ROUTE: {{cf-route}}
